ISIS3510-202510-T14/Mobile

lib/data/services/auth.dart
lib/presentation/screens/login_screen.dart
lib/presentation/screens/sign_up_screen.dart

- Styled TextFields with rounded corners, dark background, and icons inside.
- Updated "Sign In" button with purple color, rounded shape, and larger padding.
- Styled "Forgot Password?" & "Sign Up" links with contrasting colors.
- Added logo using Image.asset.
- Implemented fade-in animation for smooth screen entry.
- Refactored sign-in logic with Firebase authentication handling.
Closes #2

Feature/Login View

---

lib/data/models/location_model.dart
lib/data/models/match_model.dart
lib/presentation/screens/matches_view.dart
lib/presentation/viewmodels/matches_view_model.dart
lib/presentation/widgets/finished_match_card.dart
lib/presentation/widgets/live_match_card.dart
lib/presentation/widgets/match_card.dart
pubspec.yaml

- Added LocationModel to represent the location of a match
- Modified ViewModel to fetch matches from the backend API
- Modified MatchesView to display matches from the backend API
- Modified MatchModel to include location information
- Closes #22

feat: Connected matches view to backend API

---

android/app/build.gradle.kts
android/app/src/main/AndroidManifest.xml
android/build.gradle.kts
lib/main.dart
lib/presentation/screens/matches_view.dart
lib/presentation/viewmodels/matches_view_model.dart
pubspec.lock
pubspec.yaml

- Now when a user is near a sport event, they will receive a notification
- The notification will contain the name of the event and the distance to it
- Leaved placeholder for implement attendance notifications
- Closes #15

- Added proximity notifications

---

lib/presentation/viewmodels/matches_view_model.dart

- Now when a user is detected in a live match, the user will be notified to place a bet on the match
- Completed placeholder in matches_view_model.dart for the user bet notifications
- Closes #14

- Added user bet notifications

---

lib/presentation/screens/home_screen.dart
lib/presentation/screens/login_screen.dart

navbar implementation functionality
Closes #4

navbar implementation

---

lib/presentation/screens/login_screen.dart

Fixed problem with missing import

fix: added missing import in login screen

---

lib/presentation/screens/place_bet_view.dart
lib/presentation/viewmodels/bet_viewmodel.dart

place bet view

---

lib/data/models/bet_model.dart
lib/data/models/recommended_bet_model.dart
lib/data/repositories/bet_repository.dart
lib/data/repositories/match_repository.dart
lib/data/repositories/recommended_bet_repository.dart
lib/data/services/database_helper.dart
pubspec.lock
pubspec.yaml

- Added SQL database for local storage
- Created models for Bet and RecommendedBet
- Created repositories for Bet, Match, and RecommendedBet
- Implemented database helper for managing SQL operations
- Updated dependencies for sqflite
- Close #44

Feat: Added sql database for local storage

---

lib/data/models/match_model.dart
lib/data/repositories/favorite_repository.dart
lib/data/services/database_helper.dart
lib/presentation/screens/matches_view.dart
lib/presentation/viewmodels/matches_view_model.dart
lib/presentation/widgets/favorite_button.dart
lib/presentation/widgets/finished_match_card.dart
lib/presentation/widgets/live_match_card.dart
lib/presentation/widgets/match_card.dart

- Implemented a new FavoriteButton widget to allow users to bookmark matches.
- Integrated the FavoriteButton into UpcomingMatchCard, LiveMatchCard and FinishedMatchCard.
- Integrated a Favorite relation in the local database for storing favorite matches.
- Created a FavoriteRepository to handle database operations related to favorites.
- Updated MatchesViewModel to fetch favorite matches from the local DB.
- Updated MatchesView to display a button for filtering favorite matches.

Feat : Added favorite functionality to match cards

---

lib/data/services/connectivity_service.dart
lib/main.dart
lib/presentation/screens/matches_view.dart
lib/presentation/viewmodels/matches_view_model.dart
pubspec.lock
pubspec.yaml

- Added a utility to check network connectivity status. It notifies listeners when the connectivity status changes.
- Modified `MatchesViewModel` to use the connectivity utility.
- Inyected the utility globally in the main.dart trough a change notifier provider.
- Added dependency to `connectivity_plus` in pubspec.yaml.
- Close #40

- Feat: Added connectivity detection utility

---

lib/data/models/match_model.dart
lib/data/repositories/favorite_repository.dart
lib/presentation/viewmodels/matches_view_model.dart
lib/presentation/widgets/finished_match_card.dart
lib/presentation/widgets/live_match_card.dart
lib/presentation/widgets/match_card.dart
pubspec.lock
pubspec.yaml

- Added dependency in pubspec.yaml for cached_network_image
- Updated all match card widgets to use CachedNetworkImage for team images
- Close #43

Feat: Implement caching for team images

---

lib/presentation/screens/place_bet_view.dart
lib/presentation/screens/recommended_bet_screen.dart
lib/presentation/screens/sign_up_screen.dart
lib/presentation/screens/user_bets_screen.dart
lib/presentation/widgets/finished_match_card.dart
lib/presentation/widgets/live_match_card.dart
lib/presentation/widgets/match_card.dart

Feature/aesthetic improvement #58

---

devtools_options.yaml
lib/data/models/bet_model.dart
lib/data/models/match_model.dart
lib/data/repositories/bet_repository.dart
lib/data/services/backend_api.dart
lib/data/services/database_helper.dart
lib/data/services/draft_sync_service.dart
lib/main.dart
lib/presentation/screens/place_bet_view.dart
lib/presentation/viewmodels/bet_viewmodel.dart
lib/presentation/viewmodels/matches_view_model.dart
lib/presentation/viewmodels/user_bets_view_model.dart
lib/presentation/widgets/live_match_card.dart
lib/presentation/widgets/match_card.dart
lib/presentation/widgets/sync_status_listener.dart

Feature/ec place bet #42

---

lib/data/services/background_sync_service.dart
lib/data/services/draft_sync_service.dart
lib/data/services/isolate_manager.dart
lib/main.dart
pubspec.lock
pubspec.yaml

multi threading for sync bets

---

lib/data/services/database_helper.dart
lib/presentation/screens/recommended_bet_screen.dart
lib/presentation/viewmodels/recommended_bet_viewmodel.dart

This pull request introduces several enhancements to the recommended bets feature, including database optimizations, improved offline support, and UI updates. The key changes include adding batch insertion with auto-pruning for recommended bets, enhancing the `RecommendedBetsViewModel` to handle offline scenarios, and updating the UI to display an offline banner when the app is not connected to the internet.
Close #52
* Enhanced `RecommendedBetsViewModel` to check connectivity status using `connectivity_plus` and fetch cached bets from the local repository when offline. If online, it fetches bets from the API and caches them locally. (`lib/presentation/viewmodels/recommended_bet_viewmodel.dart`, [lib/presentation/viewmodels/recommended_bet_viewmodel.dartL1-L50](diffhunk://#diff-f72d0c35931 …

[ #52 ] Implement EC and local storage for recommended bets

---

lib/data/repositories/bet_repository.dart
lib/data/services/database_helper.dart
lib/presentation/viewmodels/user_bets_view_model.dart

Fix/place bet local storage bugs #66

---

android/app/build.gradle.kts
lib/data/services/backend_api.dart
lib/data/services/isolate_manager.dart
lib/presentation/viewmodels/bet_viewmodel.dart
lib/presentation/viewmodels/matches_view_model.dart
lib/presentation/viewmodels/recommended_bet_viewmodel.dart
lib/presentation/viewmodels/user_bets_view_model.dart
lib/src/config.dart

- Added Config.apiBaseUrl to manage API base URL
- Updated view models to use Config.apiBaseUrl
- Updated build.gradle.kts for release build configuration

Configure release build and dynamic API base URL:

---

.gitignore
lib/data/services/backend_api.dart
lib/data/services/isolate_manager.dart
lib/data/services/metrics_db_helper.dart
lib/data/services/metrics_management.dart
lib/presentation/viewmodels/bet_viewmodel.dart
lib/presentation/viewmodels/matches_view_model.dart
lib/presentation/viewmodels/recommended_bet_viewmodel.dart
lib/presentation/viewmodels/user_bets_view_model.dart

Close #63 
This pull request introduces a comprehensive API metrics logging system across multiple files, enabling better tracking of API performance and error handling. The changes include adding a database helper for storing metrics, implementing a metrics management module, and integrating these functionalities into various service and viewmodel classes.
* [`lib/data/services/metrics_db_helper.dart`](diffhunk://#diff-db3c24d8dda8039ce1bc520a51436e362dcfc969d01bf600d6e1a7b14b22f1bdR1-R49): Added a new `MetricsDatabase` class to manage a SQLite database for storing API metrics, including endpoint, duration, status code, success flag, error message, and timestamp.
* [`lib/data/services/metrics_management.dart`](diffhunk://#diff-62c7365a4b2011e29b5e2459ab68a8525155a4cf2520041633b11a97bab650 …

[ #63 ] Implement BQ of Average Response Time from Endpoint

---

.gitignore
lib/data/services/upload_service.dart
lib/main.dart
pubspec.lock
pubspec.yaml

Feature/improve bq connection errors #67

---

lib/data/models/product_model.dart
lib/data/repositories/product_repository.dart
lib/data/services/database_helper.dart
lib/presentation/screens/home_screen.dart
lib/presentation/screens/marketplace_screen.dart
lib/presentation/viewmodels/marketplace_viewmodel.dart

implement marketplace view

---

lib/presentation/widgets/live_match_card.dart

Fix/improve live matches aesthetics #75

---

lib/data/services/user_metrics_service.dart
lib/main.dart
lib/presentation/screens/create_account_screen.dart
lib/presentation/screens/place_bet_view.dart

Feature/bq regretful users #79

---

lib/data/models/product_model.dart
lib/data/services/database_helper.dart
lib/data/services/productView_sync_service.dart
lib/presentation/viewmodels/product_detail_viewmodel.dart

- Added a syncing service to sync product view data between the app and the database.
- Implemented the syncing logic in the product detail view model.
- Modified product model to corretly map the product id from the request.
- Updated the database helper to handle the new syncing service.
- Closes #87

Added syncing bween product view and database

---

lib/presentation/screens/matches_view.dart
lib/presentation/viewmodels/matches_view_model.dart

- Refactor match status bucketing to a single pass
- Cache AndroidNotificationDetails as static const to eliminate per-call allocations
- Added itemExtent/cacheExtent hints to ListView for smoother scrolling
- Close #89

Micro-opt for matches view

---

lib/data/services/database_helper.dart
lib/main.dart
lib/presentation/screens/cart_screen.dart
lib/presentation/viewmodels/cart_viewmodel.dart

This pull request introduces a significant update to the cart functionality by integrating offline support with a local SQLite database and enhancing the `CartViewModel` to handle synchronization between the local database and the UI. Additionally, it includes UI improvements to handle offline scenarios and backend integration for purchases.
Closes #94 
* Updated the database schema to version 8 and added a new `cart_items` table to store cart data locally. (`lib/data/services/database_helper.dart`: [[1]](diffhunk://#diff-ff3191e26fc22457d647dd227b5d4d89958bd40b0abbf6de3c1104ad9c007e92L42-R42) [[2]](diffhunk://#diff-ff3191e26fc22457d647dd227b5d4d89958bd40b0abbf6de3c1104ad9c007e92L102-R112) [[3]](diffhunk://#diff-ff3191e26fc22457d647dd227b5d4d89958bd40b0abbf6de3c1104ad9c007e92R229-R240)
* …

[ #94 ] Connectivity and Persistence Strategy for Shopping Cart

---

lib/presentation/screens/matches_view.dart

Increased item extent to prevent overflow
